import { LicenseGuardian } from './src/memory/licenseGuardian';
import { AriesCore } from './src/AriesCore';
import * as fs from 'fs';

async function runPardonTest() {
    console.log("=== ARIES PARDON & CLEAN RESTORATION TEST ===\n");

    const userId = "USER_PRO_HACKER";
    const LOCK_FILE = '.sys_lock';
    const MEMORY_FILE = 'sovereign_memory.json';

    // 1. MASTER ACTION: Hapus Blokir & Hapus Data yang Terkontaminasi (Wipe)
    console.log("[MASTER ACTION] Menghapus blokir...");
    if (fs.existsSync(LOCK_FILE)) fs.unlinkSync(LOCK_FILE);

    console.log("[MASTER ACTION] Menghapus memori yang terenkripsi (Fresh Start)...");
    if (fs.existsSync(MEMORY_FILE)) fs.unlinkSync(MEMORY_FILE);

    // 2. Berikan Signature SAH (Generated by Master)
    const SECRET_SALT = 'MASTER_SECRET_KEY_ARIES';
    const crypto = require('crypto');
    const validSignature = crypto
      .createHmac('sha256', SECRET_SALT)
      .update(`PRO:${userId}`)
      .digest('hex');

    // 3. Tes Akses Kembali
    console.log("\nTesting: Mencoba akses kembali dengan sistem bersih...");
    const aries = new AriesCore(userId, "PRO", validSignature);
    
    try {
        const result = await aries.processChat("Halo Aries, saya kembali.", "Selamat datang kembali, Master.");
        console.log(`Status: ${result.status}`);
        console.log(`AI Response: ${result.data}`);
        console.log("\n[VERIFIED] Sistem pulih sempurna.");
    } catch (error) {
        console.log("\n[ERROR] Masih ada sisa data rusak: " + error.message);
    }
}

runPardonTest();
